### ISSUE TITLE
0.10.2-mod-2+dev.7818b7de: AttributeError: the intent attribute can only be used after starting

### ISSUE THREAD

**Issue by jaller94** [vector-im/mautrix-telegram#21]
`one-staging` is crashlooping with this.

```
[2021-11-22 22:40:41,217] [INFO@mau.init] Initializing mautrix-telegram 0.10.2-mod-2+dev.7818b7de
[2021-11-22 22:40:41,432] [CRITICAL@mau.init] Unexpected error in initialization
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 93, in _prepare
    self.prepare()
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 89, in prepare
    self.prepare_bridge()
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/__main__.py", line 101, in prepare_bridge
    init_users_task = init_user(context)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 699, in init
    return asyncio.gather(*(sem_task(task) for task in tasks))
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 699, in <genexpr>
    return asyncio.gather(*(sem_task(task) for task in tasks))
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 695, in <genexpr>
    tasks = (User.from_db(db_user).try_ensure_started()
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 191, in from_db
    return User(db_user.mxid, db_user.tgid, db_user.tg_username, db_user.tg_phone,
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 96, in __init__
    self.db_contacts = db_contacts
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 145, in db_contacts
    self.contacts = [pu.Puppet.get(entry) for entry in contacts] if contacts else []
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 145, in <listcomp>
    self.contacts = [pu.Puppet.get(entry) for entry in contacts] if contacts else []
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/puppet.py", line 377, in get
    return cls.from_db(puppet)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/puppet.py", line 187, in from_db
    return Puppet(db_puppet.id, db_puppet.access_token, db_puppet.custom_mxid,
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/puppet.py", line 116, in __init__
    self.default_mxid_intent = self.az.intent.user(self.default_mxid)
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/appservice.py", line 119, in intent
    raise AttributeError("the intent attribute can only be used after starting")
AttributeError: the intent attribute can only be used after starting
```

### Code in question
https://github.com/vector-im/mautrix-telegram/blob/670283134bb182de6523531732fecd0c11692fec/mautrix_telegram/puppet.py#L116

### PR that looks like it could be responsible
https://github.com/vector-im/mautrix-telegram/pull/20

**Comment by jaller94** [comment]
@Half-Shot This got fixed and can be closed, right?
I didn't encounter this issue with the -mod-3 release nor `master`.

**Comment by Half-Shot** [comment]
Yeah, think we did fix it.
