### ISSUE TITLE
active_puppet_metric: float() argument must be a string or a number, not 'coroutine'

### ISSUE THREAD

**Issue by jaller94** [vector-im/mautrix-telegram#41]
```
 [ERROR@mau.init] Error while checking: float() argument must be a string or a number, not 'coroutine'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/__main__.py", line 233, in _loop_active_puppet_metric
    await self._update_active_puppet_metric()
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/__main__.py", line 223, in _update_active_puppet_metric
    METRIC_ACTIVE_PUPPETS.set(active_users)
  File "/usr/lib/python3.9/site-packages/prometheus_client/metrics.py", line 386, in set
    self._value.set(float(value))
TypeError: float() argument must be a string or a number, not 'coroutine'
```

## Affected verions
* mautrix-telegram-v0.11.0-mod-1e

## Code in question

https://github.com/vector-im/mautrix-telegram/blob/eb74b300229fe67b73c4bdc9a867b273ac9bdba6/mautrix_telegram/__main__.py#L236-L246

**Comment by jaller94** [comment]
## Code in question
https://github.com/vector-im/mautrix-telegram/blob/eb74b300229fe67b73c4bdc9a867b273ac9bdba6/mautrix_telegram/__main__.py#L232

Likely a missing `await`.

**Comment by jaller94** [comment]
Not reproducible with `mautrix-telegram-v0.11.0-mod-3`.
